name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Debug

    - name: Run tests
      run: dotnet test --no-build --verbosity detailed ./github-action-sample-tests/github-action-sample-tests.csproj

  code_analysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=myorganization
          -Dsonar.projectKey=myproject
          -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Trivy Security Scan
      uses: aquasecurity/trivy-action@v0.10.1
      with:
        scan-type: 'fs'
        input: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, code_analysis]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Application (Simulated)
      run: echo "Deploy step placeholder. Customize for your specific deployment process."
